services:
  - type: web
    name: 2d-animator-cursor-api
    runtime: node
    rootDirectory: Backend
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000